### ISSUE TITLE
[Feature]: add text-to-singing 🎤🎵

### ISSUE THREAD

**Issue by funmolde** [Ryouko-Yamanda65777/vc#1]
Hello 😀,
I'd like to suggest adding a text-to-singing voice synthesis feature.
https://github.com/topics/singing-voice-synthesis
Thank you -_-

**Comment by Ryouko-Yamanda65777** [comment]
can you give one of the repos?

**Comment by funmolde** [comment]
> can you give one of the repos?

ok https://github.com/espnet/espnet

**Comment by Ryouko-Yamanda65777** [comment]
okay i'll see

**Comment by Ryouko-Yamanda65777** [comment]
maybe this kinda complex to add, i'll try

**Comment by Ryouko-Yamanda65777** [comment]
don't forgot to check new repo https://github.com/Ryouko-Yamanda65777/RVC

**Comment by Ryouko-Yamanda65777** [comment]
maybe i'll add one of espnet's feture

**Comment by Ryouko-Yamanda65777** [comment]
or maybe other work espnet is kinda error idk why

**Comment by Ryouko-Yamanda65777** [comment]
sorry, its to hard to make myself

**Comment by funmolde** [comment]
ok tank you
